#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME "2026.04-pre"
#define PROJECT_VERSION_HASH "795ccb2*"
#define PROJECT_VERSION "2026.04-pre (795ccb2*)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
