#ifndef OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define BUILD_TIMESTAMP "2026-03-05 at 14:29:06 hrs"
#endif // OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
